---
latitude: 42.35061
longitude: -71.06827
map_zoom: 12
name: Revere Hotel Boston Common
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 200 Stuart St
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02116'
_hotel_id: REV457
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
